theme: jekyll-theme-minimal
title: ğŸ“„ğŸ–Šï¸ğŸ’»âœ¨
description: | 
  Hi, it's Mary Antonette Tanael. 
  Welcome to my technical writing portfolio.
  
  ## ğŸ“ Site navigation

  [About me](https://marytanaelwriter.github.io/portfolio/about-me.html)  
  [Sample 1: Process document](https://marytanaelwriter.github.io/portfolio/sample-1-overview.html)  
  [Sample 2: Installation guide](https://marytanaelwriter.github.io/portfolio/sample-2-overview.html)  
  [Sample 3: How-to guide](https://marytanaelwriter.github.io/portfolio/sample-3-overview.html)  
#logo: logo-writer2.png
