  
theme: jekyll-theme-minimal
title: ğŸ“„ğŸ–Šï¸ğŸ’»âœ¨
description: Mary Antonette Tanael's tech writing portfolio

## ğŸ“ Navigation

[Sample 1: Process document](samples/sample-1-overview.md)  
[Sample 2: Installation guide](samples/sample-2-overview.md)  
[Sample 3: How-to guide](samples/sample-3-overview.md)  
