theme: jekyll-theme-minimal
title: ğŸ“„ğŸ–Šï¸ğŸ’»âœ¨
description: | 
  Hi, it's Mary Antonette Tanael. 
  Welcome to my technical writing portfolio.
  
  ## ğŸ“ Site navigation

  [About me](about-me.md)  
  [Sample 1: Process document](sample-1-overview.md)  
  [Sample 2: Installation guide](sample-2-overview.md)  
  [Sample 3: How-to guide](sample-3-overview.md)  
logo: logo-writer2.png
