theme: jekyll-theme-minimal
title: ğŸ“„ğŸ–Šï¸ğŸ’»âœ¨
description: | 
  Hi, it's Mary Antonette Tanael. 
  Welcome to my technical writing portfolio.
sample1:
  url: https://marytanaelwriter.github.io/portfolio/sample-1-overview.html
